name: Create and publish image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push-image:
    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Call CD webhook to start latest image
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: "https://cd.dev.jdav-freiburg.de/v1/update"
          webhook_auth: ${{ secrets.CD_DEPLOYMENT_KEY }}
          webhook_auth_type: "bearer"
          timeout: 10 # timeout for making the initial connection
          max_time: 240 # only returns when update is done, so we need to wait a bit
          curl_opts: '--retry 2' # retry 2 times if the connection fails

